services:
  aiportal:
    image: 202.5.253.162:443/ffm-hub/aiportal:0.0.11
    container_name: aiportal
    ports:
      - "80:8443"
    volumes:
      - ./keystore.p12:/app/certs/keystore.p12
    environment:
      - SPRING_PROFILES_ACTIVE=stage
      - APIMODULE_URL=http://${VM_IP}:8080
      - FRONTEND_KEYCLOAK_URL=https://${VM_IP}:8443
      - FRONTEND_KEYCLOAK_REALM=ffm-realm
      - FRONTEND_KEYCLOAK_CLIENTID=ffm
      - SERVER_PORT=8443
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_KEYSTORE=/app/certs/keystore.p12
      - SERVER_SSL_KEYSTORE_PASSWORD=changeit
      - SERVER_SSL_KEYSTORE_TYPE=PKCS12

  api-relay:
    image: 202.5.253.162:443/ffm-hub/api-relay:0.0.11
    container_name: api-relay
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/vllm_test:/opt/vllm_test
    environment:
      - KEYCLOAK_SERVER_URL=https://${VM_IP}:8443
      - VLLM_HOST=${VM_IP}

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.0
    container_name: keycloak
    ports:
      - "8443:8443"
    volumes:
      - ./keycloak.crt.pem:/opt/keycloak/conf/keycloak.crt.pem
      - ./keycloak.key.pem:/opt/keycloak/conf/keycloak.key.pem
      - ./ffm-hub.json:/opt/keycloak/data/import/ffm-hub.json
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTPS_ENABLED=true
      - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/conf/keycloak.crt.pem
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/conf/keycloak.key.pem
      - KC_HEALTH_ENABLED=true
    command: start-dev --import-realm --health-enabled